title: Falling Comet Lab
description: Arduino x 數學教學
baseurl: ""
url: "https://RubyChengLab.github.io"
permalink: /:categories/:title/
github_username: RubyChengLab
email: fallingcometlab@gmail.com

markdown: kramdown
highlighter: rouge

kramdown:
  math_engine: mathjax
  input: GFM
include:
  - images
  - projects.html
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
